### ISSUE TITLE
Reload Command

### ISSUE THREAD

**Issue by cubesih** [v1cow/SimpleMaintenance#2]
Hello, I'm requesting this on the behalf of me and other users who are utilizing this plugin.

/maintenance reload - Reloads the configuration after the command is performed.

Hopefully, you can find some time to approve and consider this change?

**Comment by v1cow** [comment]
Hello, I have intentions to write a reload command into this plugin in the future.

From my POV, I'm actually wondering if I should write a plugin manager itself, or a reload command for this plugin.

Thank you for this review.
